# Generated by Django 3.2.13 on 2023-05-18 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmdb_id', models.CharField(max_length=100)),
                ('kmdb_seq', models.CharField(max_length=100)),
                ('movie_title', models.CharField(max_length=200)),
                ('director_name', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=100)),
                ('plot', models.TextField()),
                ('runtime', models.CharField(max_length=100)),
                ('rating', models.TextField()),
                ('release_date', models.CharField(max_length=100)),
                ('keywords', models.TextField()),
                ('poster', models.URLField()),
                ('teaser', models.URLField()),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField()),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.location')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='movies',
            field=models.ManyToManyField(related_name='total_location', through='movies.LocationDetail', to='movies.Movies'),
        ),
    ]
